#! /usr/bin/env bash

## Script to remove all docker containers and volumes. Useful for
## local development. Use with care.

printf "Removing %s ...\n" "containers"
docker ps -a -q |
  while read -r f; do
    docker stop "${f}"
    docker rm "${f}"
  done

printf "Removing %s ...\n" "volumes"
docker volume ls -q |
  while read -r f; do
    docker volume rm "${f}"
  done

printf "Removing %s ...\n" "networks"
docker network ls -q |
  while read -r f; do
    docker network rm "${f}"
  done
